### PR TITLE
refactor obstacle

### PR DESCRIPTION
**Pull request by Olllom**
This PR unifies the 2D and 3D obstacle code.
It also changes the constructor so that it only takes arguments in physical units.

Let me know what you think.

### CODE REVIEW

**Comment by Olllom** [comment]
example: https://github.com/lettucecfd/lettuce/blob/obstacle/examples/obstacle.ipynb

**Comment by MartinKliemank** [comment]
Sorry for taking so long.
Seems good to me, when #115 popped up I was also wondering, why there wasn't any option to change the characteristic length in PU. 
There are other parameter constellations that work (like a shape in PU, and `char_len` in both PU and LU which might be closest to how it is usually described in papers), however I'm not sure if any of them is better than the one you chose.

**Comment by MartinKliemank** [comment]
In the branch I'm on there is the [`Regular_Grid` class](https://github.com/MartinKliemank/lettuce/blob/lettuceMPI/lettuce/grid.py), which I've been using since a year now. It takes shape in LU, and char_len in both LU and PU. We should probably look into how that fits this and the other flows / general implementation and possible parallelization at some point.

**Comment by Olllom** [comment]
@MartinKliemank OK, great. Thanks for commenting. The regular grid class looks interesting. I have a similar design in mind but I may borrow some of your code at some point.

**Comment by Olllom** [comment]
ok, this is ready to go on my end.

**Pull request merged**
