### PR TITLE
improved porous media

### PR DESCRIPTION
**Pull request by je-santos**
Hey guys,

I checked the units and added a couple things that are commonly done in the pore-scale world. 

let me know what you think.

Best,
Javier

### CODE REVIEW

**Comment by Olllom** [comment]
Wow. This looks awesome. Thank you so much. 

Do you have any feedback on what we could improve in the library code based on your work on this notebook? Maybe we could offer a different way of building the `units` object based on a user-defined `tau` rather than the Reynolds number. This could be easily added through a static constructor. If there's anything else you would have liked differently, let us know or feel free to open a PR.

And by the way: Does the resulting permeability make sense?

**Comment by je-santos** [comment]
Yeah, lettuce works like a charm. The permeability makes total sense.
I'll benchmark a 3D case with lettuce and Palabos and let you guys know how it went.

Feature-wise, I have 2 questions:

o. Would it be possible to have a "trainable" mask? So it would be possible to backpropagate through the solid geometry. It would be interesting to investigate how geometry affects material properties. Maybe along the lines of [gray-lbm](https://gitlab.com/unigespc/palabos/-/tree/master/examples/showCases/partialBounceBack), perhaps?

o. Do you guys have plans of implementing a 2-phase Shan-Chen model?

Many thanks for your hard-work. I'll put lettuce to good use :)

**Comment by Olllom** [comment]
Implementing a gray LBM would be very interesting. Yes, we have thought about it but have not had an immediate use case so far. Do you have a specific method in mind? We would be super happy to accept a PR on this but might also do some development in this direction in the future.

Regarding multiphase flow: it should be quite easy to use the existing `BGKCollision` and `Guo` force for implementing a liquid/gas Shan-Chen model. Probably you just have to subclass `BGKCollision` and recompute `self.force.acceleration` from `rho` [here](https://github.com/lettucecfd/lettuce/blob/9455449b997eb245cd714c5759d7a7cd4c33b1dc/lettuce/collision.py#L23). You could maybe use [this](https://github.com/lettucecfd/lettuce/blob/9455449b997eb245cd714c5759d7a7cd4c33b1dc/lettuce/util.py#L36) to compute the density gradients in the pseudopotential.

If you want more complex behavior such as multiple components, wetability, contact angles, higher-order isotropy, etc. that would take a bit more effort. We have done some work, e.g. [this](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.97.023313), on multiphase simulations pre-lettuce but have no current plans of continuing our research along those lines.

**Comment by Olllom** [comment]
See https://github.com/lettucecfd/lettuce/pull/101 for a rudimentary multiphase example.

**Pull request merged**
