### PR TITLE
change readme install instructions

### LINKED ISSUE #170: Update Requirements and CI for Compatibility with Torch 2.4
We need to verify and update our project's requirements and continuous integration (CI) configurations to ensure compatibility with the new Torch 2.4 package. This involves updating dependency files, running tests, and making any necessary adjustments to our CI setup.

### LINKED ISSUE #234: [Feature]: change readme install instructions
Ideally, we want users to be able to install directly from `requirements.txt` - if they are using a compatible GPU

### PR DESCRIPTION
**Pull request by PhiSpel**
## Description

- [x] updated requirements to be used directly in PyCharm or conda
- [x] updated Readme
- [x] **Note**: approximate package requirements (`~=`) are not recognized by Conda
- [x] **Note for Readme**: one may need to manually specify the `CUDA_HOME` variable for native (to the package folder `.../cudatoolkit_*` containing `/bin/nvcc`)

closes #170
closes #234 

## Checklist

 - [x] This pull request is associated to an issue
 - [x] This PR contains a description
 - [x] Add someone else as reviewer and wait for approval before merging.

### CODE REVIEW

**Comment by PhiSpel** [comment]
my best bet for installation:

```
git clone https://github.com/lettucecfd/lettuce.git lettuce
cd lettuce
conda create -n lettuce
conda activate lettuce
conda install --yes --file requirements.txt
python setup.py develop
lettuce convergence
pytest tests
```

for now:

```
git clone https://github.com/lettucecfd/lettuce.git lettucetest
cd lettucetest
git fetch origin
git checkout 234-feature-change-readme-install-instructions
conda create -n lettucetest
conda activate lettucetest
conda install --yes --file requirements.txt
python setup.py develop
lettuce convergence
pytest tests
```

**Comment by PhiSpel** [comment]
@McBs

- [ ] do we need exact restricitons for `packaging`, `click` and `setuptools`?
- [ ] can you check if the instructions above or, ideally, in the new readme work for you?

**Comment by McBs** [comment]
> @McBs
> 
>     * [x]  do we need exact restricitons for `packaging`, `click` and `setuptools`?
> 
>     * [x]  can you check if the instructions above or, ideally, in the new readme work for you?

Hi @PhiSpel 
the instructions work on my workstation :-)

**Review by McBs — APPROVED** [review]
lgtm

**Pull request merged**
